### ISSUE TITLE
is_swap_script_v1.js seems to throw for some transactions

### ISSUE THREAD

**Issue by johnzweng** [alexbosworth/goldengate#2]
When running `bos accounting chain-fees` I run into the following error:

```
bos@liquidblitz:~/balanceofsatoshis $ bos accounting chain-fees

err:
  - 503
  - FailedToMapChainReceivesToRecords
  -
    err:
      message: Cannot read property 'length' of null
      stack:
        - TypeError: Cannot read property 'length' of null
        -     at module.exports (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/goldengate/script/is_script_matching_template.js:37:18)
        -     at module.exports (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/goldengate/script/is_swap_script_v1.js:47:10)
        -     at module.exports (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/goldengate/script/version_of_swap_script.js:25:7)
        -     at module.exports (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/goldengate/transactions/is_sweep.js:58:21)
        -     at module.exports (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/harmony/notes_for_chain_transaction.js:19:42)
        -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/harmony/chain_receives_as_records.js:58:14
        -     at Array.map (<anonymous>)
        -     at module.exports (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/harmony/chain_receives_as_records.js:53:6)
        -     at asyncAuto.chainReceives (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/report/get_accounting_report.js:302:29)
        -     at runTask (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:227:13)
        -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:167:31
        -     at processQueue (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:177:13)
        -     at taskComplete (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:193:9)
        -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/auto.js:220:17
        -     at /home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/async/internal/onlyOnce.js:12:16
        -     at asyncAuto.channelTxIds (/home/bos/.npm-global/lib/node_modules/balanceofsatoshis/node_modules/ln-accounting/report/get_accounting_report.js:292:16)
```

If it helps for debugging, the error happens when processing [this transaction](https://blockchair.com/bitcoin/transaction/571eac1efe55f030f536da654970b4e4761d04a09abc17f1d9e4f297395e0313), so [is_sweep.js:29](https://github.com/alexbosworth/goldengate/blob/master/transactions/is_sweep.js#L29) gets called with this hex transaction string: 
```
010000000001019833d8fd16fab01622ba4d371235b1c5d57990387c657924f748e25fe561616f0000000000ffffffff02059908000000000017a9146a8a2c36b65f2b573db7cec9c8673bf251f70df687d04f0d000000000016001430698b1cdae5e4910f97eadb3d5e888a9f66382802483045022100c5c21672f037cb64b226012a8143e8873e2c2ede8c749eb77bf3c3ea2435c62002203d2aa35e29f8f815677fb62776dbb5c6d8bea6e69bc9d1fb9217a3b539b377e8012103413d803cccdb408ed3144d56323d89508566e03a4b0b757a62d28e4505e75b8100000000
```

**Comment by alexbosworth** [comment]
Can you post what version you are running?

**Comment by alexbosworth** [comment]
Ah I think I see the issue hold on for a fix

**Comment by alexbosworth** [comment]
Should be fixed now

**Comment by johnzweng** [comment]
Thanks! Yes, it's working now in bos 5.46.9. 👍
